RECONCILIATION_SECRET_KEY="django-insecure-hrkja8p0$^p0b#kus-rpcv9yklie*3s-2)ynp4kd671r1h9+^$"
RECONCILIATION_DEBUG=true
RECONCILIATION_ALLOWED_HOSTS="127.0.0.1,localhost"
RECONCILIATION_TRUSTED_ORIGINS="http://127.0.0.1:3000,http://localhost:3000"

# Database env variables
RECONCILIATION_DATABASE_ENGINE="django.db.backends.postgresql"
RECONCILIATION_DATABASE_NAME="goye"
RECONCILIATION_DATABASE_USER="postgres"
RECONCILIATION_DATABASE_PASSWORD="password"
RECONCILIATION_DATABASE_HOST="localhost"
RECONCILIATION_DATABASE_PORT="5432"

# Google cloud env variables
RECONCILIATION_GCLOUD_SUPPORT=false
RECONCILIATION_GOOGLE_APPLICATION_CREDENTIALS="path/to/google-credentials.json"
RECONCILIATION_GS_BUCKET_NAME="data-reconciliation"

# celery env variables
RECONCILIATION_CELERY_BROKER_URL="redis://localhost:6379/0"
RECONCILIATION_CELERY_RESULT_BACKEND="redis://localhost:6379/0"
